In [1]:
#!pip install -r requirements.txt

In [3]:
import pandas as pd
import numpy as np

In [4]:
stage = pd.read_json('full_stage_data.json')

In [5]:
stage.drop(['indices','feature_type'],axis=1, inplace=True)
stage

,lat,lon,elev,delta_dist,dist,gradient,max_gradient,min_gradient,climb_length,segment_type,difficulty,Stamina,Sprint,Climbing,Flat,Technique,Downhill,Hills,Aggressiveness,Teamwork
0,45.64987,7.71266,354.0,594.039658,594.039658,-0.168339,0.000000,0.000000,594.039658,Flat,0.000000,0.000347,0,0.000000,0.153793,0.256321,0.000000,0.0,0.205057,0.384482
1,45.64640,7.71745,353.0,536.604961,1130.644619,-0.186357,0.000000,0.000000,536.604961,Flat,0.000000,0.000660,0,0.000000,0.153745,0.256241,0.000000,0.0,0.204993,0.384362
2,45.64195,7.71825,355.0,513.233769,1643.878388,0.389686,0.543946,0.000000,513.233769,Flat,0.649477,0.000959,0,0.000000,0.153699,0.256164,0.000000,0.0,0.204932,0.384247
3,45.63752,7.71961,361.0,503.866161,2147.744549,1.190792,2.579881,-1.650925,503.866161,Flat,1.984654,0.001253,0,0.000000,0.153653,0.256089,0.000000,0.0,0.204871,0.384134
4,45.63379,7.72483,356.0,596.193138,2743.937687,-0.838654,0.000000,-2.376183,596.193138,Flat,0.000000,0.001601,0,0.000000,0.153600,0.256000,0.000000,0.0,0.204800,0.384000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,45.30271,7.20269,1613.0,549.454213,132301.193298,10.555930,13.341385,3.196049,8058.387722,Climbing ND,86.066947,0.297678,0,0.634976,0.000000,0.000000,0.000000,0.0,0.000000,0.067346
240,45.30224,7.19851,1658.0,519.579293,132820.772591,8.660853,8.660853,0.000000,8058.387722,Climbing ND,75.486104,0.298847,0,0.633919,0.000000,0.000000,0.000000,0.0,0.000000,0.067234
241,45.30255,7.19706,1691.0,552.856894,133373.629485,5.968995,17.358545,-3.621573,8058.387722,Climbing,60.456561,0.222289,0,0.456905,0.000000,0.097214,0.194428,0.0,0.000000,0.029164
242,45.30292,7.19534,1725.0,501.349784,133874.979269,6.781692,7.685170,2.298564,8058.387722,Climbing ND,64.994122,0.301219,0,0.631775,0.000000,0.000000,0.000000,0.0,0.000000,0.067006
243,45.30260,7.18957,1758.0,543.565535,134418.544804,6.071025,10.740176,-4.983182,8058.387722,Climbing,61.026230,0.224031,0,0.455882,0.000000,0.096996,0.193992,0.0,0.000000,0.029099

In [6]:
def weighted_mean(values, weights):
    return (values * weights).sum() / weights.sum()

In [7]:
global_value = stage[['Stamina',
       'Sprint', 'Climbing', 'Flat', 'Technique', 'Downhill', 'Hills',
       'Aggressiveness', 'Teamwork']].agg(
            Stamina=('Stamina', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Sprint=('Sprint', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Climbing=('Climbing', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Flat=('Flat', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Technique=('Technique', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Downhill=('Downhill', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Hills=('Hills', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Aggressiveness=('Aggressiveness', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty'])),
            Teamwork=('Teamwork', lambda x: weighted_mean(x, stage.loc[x.index, 'difficulty']))
       )[['Stamina',
       'Sprint', 'Climbing', 'Flat', 'Technique', 'Downhill', 'Hills',
       'Aggressiveness', 'Teamwork']].max()
global_value

Stamina           0.153397
Sprint            0.000000
Climbing          0.424041
Flat              0.014953
Technique         0.043334
Downhill          0.062582
Hills             0.192161
Aggressiveness    0.049859
Teamwork          0.059673
dtype: float64

In [8]:
cyclists = pd.read_json('ciclistas.json')
cyclists

,resistencia,sprint,montana,llano,paves,tecnica,descenso,colinas,agresividad,crono,trabajoequipo,salud,forma,equipo,nombre,apellido
0,91.207,80.285,7.842,93.734,99.670,89.018,11.015,67.150,41.726,14.903,32.961,99,100,Villavante,Ava,Johnson
1,62.076,25.340,0.000,16.559,0.000,10.051,0.000,0.000,1.454,1.069,0.000,52,90,Jaguar,Sophia,Miller
2,67.936,95.691,16.444,80.727,48.005,72.278,66.433,76.086,77.835,34.680,21.202,90,97,Europcar974,Sophia,Williams
3,61.044,69.027,21.612,68.464,7.387,61.358,32.151,68.499,77.463,22.388,4.981,92,99,Squadra_Pirata_24,Isabella,Davis
4,32.978,73.425,7.960,75.744,85.585,57.627,54.780,85.736,66.411,13.278,43.070,51,98,ZG,Oliver,Brown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,91.250,26.087,23.451,98.099,37.836,93.459,18.242,12.218,55.476,99.363,24.017,95,100,Sonfuga,Ava,Martinez
196,37.664,11.973,53.727,28.057,48.516,65.447,26.703,22.547,70.164,40.803,2.368,95,90,AlAndalus,William,Smith
197,84.558,19.448,61.751,94.043,68.617,96.369,32.433,12.975,45.277,98.098,24.550,85,90,TramontanaTeam,Emma,Smith
198,61.747,21.809,20.080,47.689,92.857,43.092,60.401,91.300,72.999,17.268,12.576,90,100,MortoviaCycling,Liam,Davis
199,26.562,18.543,63.841,59.475,28.756,53.369,38.394,41.949,11.180,19.362,50.202,95,90,LagunkorTeam,Ava,Martinez

In [9]:
mappings = {
    'resistencia':'Stamina',
    'sprint':'Sprint',
    'montana':'Climbing',
    'llano':'Flat',
    'tecnica':'Technique',
    'descenso':'Downhill',
    'colinas':'Hills',
    'agresividad':'Aggressiveness',
    'trabajoequipo':'Teamwork'
}

cyclists.rename(columns=mappings, inplace=True)
cyclists

,Stamina,Sprint,Climbing,Flat,paves,Technique,Downhill,Hills,Aggressiveness,crono,Teamwork,salud,forma,equipo,nombre,apellido
0,91.207,80.285,7.842,93.734,99.670,89.018,11.015,67.150,41.726,14.903,32.961,99,100,Villavante,Ava,Johnson
1,62.076,25.340,0.000,16.559,0.000,10.051,0.000,0.000,1.454,1.069,0.000,52,90,Jaguar,Sophia,Miller
2,67.936,95.691,16.444,80.727,48.005,72.278,66.433,76.086,77.835,34.680,21.202,90,97,Europcar974,Sophia,Williams
3,61.044,69.027,21.612,68.464,7.387,61.358,32.151,68.499,77.463,22.388,4.981,92,99,Squadra_Pirata_24,Isabella,Davis
4,32.978,73.425,7.960,75.744,85.585,57.627,54.780,85.736,66.411,13.278,43.070,51,98,ZG,Oliver,Brown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,91.250,26.087,23.451,98.099,37.836,93.459,18.242,12.218,55.476,99.363,24.017,95,100,Sonfuga,Ava,Martinez
196,37.664,11.973,53.727,28.057,48.516,65.447,26.703,22.547,70.164,40.803,2.368,95,90,AlAndalus,William,Smith
197,84.558,19.448,61.751,94.043,68.617,96.369,32.433,12.975,45.277,98.098,24.550,85,90,TramontanaTeam,Emma,Smith
198,61.747,21.809,20.080,47.689,92.857,43.092,60.401,91.300,72.999,17.268,12.576,90,100,MortoviaCycling,Liam,Davis
199,26.562,18.543,63.841,59.475,28.756,53.369,38.394,41.949,11.180,19.362,50.202,95,90,LagunkorTeam,Ava,Martinez

In [14]:
def compute_global_value(df, global_abilities):
    # Calculate cross product (element-wise product for matching columns)
    numeric_cols = global_abilities.index  # Columns to use from the series
    df['global_value'] = df[numeric_cols].dot(global_abilities)

    df_sorted = df.sort_values(by='global_value', ascending=False)
    
    return df_sorted

In [15]:
compute_global_value(cyclists, global_value)

,Stamina,Sprint,Climbing,Flat,paves,Technique,Downhill,Hills,Aggressiveness,crono,Teamwork,salud,forma,equipo,nombre,apellido,global_value
44,79.446,30.177,97.410,73.579,13.504,61.335,80.642,93.131,71.259,36.582,52.023,90,98,WinterIsComing,Olivia,Martinez,86.850877
27,86.545,11.120,98.996,71.798,33.104,86.445,86.618,82.268,75.043,37.978,23.014,93,100,BLOEMENAANDEMITTE,Isabella,Garcia,86.418022
132,82.801,86.152,95.520,82.991,32.572,69.932,80.521,84.403,54.006,19.323,34.557,88,99,Elgrand,Sophia,Davis,83.490143
180,89.042,70.977,97.729,77.436,60.357,56.967,80.638,76.495,70.520,73.926,24.275,90,96,Wizards,Liam,Johnson,83.436833
143,76.632,67.678,94.798,78.558,14.528,65.692,79.085,81.966,86.304,72.020,26.259,93,100,FaltososDeChigre,Olivia,Johnson,82.544678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,58.513,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,96,90,barrio,Olivia,Garcia,8.975690
73,8.225,38.965,0.000,77.140,0.000,0.000,0.000,0.000,14.063,0.000,1.505,52,90,Sauceda_LH,Emma,Williams,3.206115
74,0.000,0.000,0.000,0.000,60.010,0.000,0.000,0.000,0.000,0.000,0.000,96,90,LeganesBike,James,Williams,0.000000
8,0.000,0.000,0.000,0.000,59.994,0.000,0.000,0.000,0.000,0.000,0.000,96,90,TarracoCycling,Oliver,Johnson,0.000000
105,0.000,60.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,85,90,barrio,Liam,Davis,0.000000